#!/bin/bash
#Simple utility script for replacing all occurrences of something across the source

# Check for arguments #
if [ $# -eq 0 ]; then
	echo "usage: srcreplace [old] [new]"
	exit 0
fi

# Continue and confirm replacement operation #
echo "All occurrences of \"$1\" will be replaced with \"$2\""
read -r -p "Are you sure? [y/N]" response
case "$response" in
	[yY][eE][sS]|[yY])
		find ./ -type f -exec sed -i "s/$1/$2/g" {} \;
		;;
	*)
		echo "Operation cancelled"
		;;
	esac
